import type { StudentProfile } from '@/types/profile';
import type { Topic } from '@/types/matching';

/**
 * QA Match Agent — The "Academic Critic"
 * 
 * This agent takes a shortlisted match and evaluates it using Claude
 * based on the rigorous system prompt provided by the user.
 */

export interface QAMatchResult {
  final_confidence_score: number;
  match_tier: 'Perfect Fit' | 'Strong Candidate' | 'Stretch Goal' | 'Misaligned';
  technical_reality_check: {
    is_feasible: boolean;
    identified_gaps: string[];
    strongest_assets: string[];
  };
  student_facing_rationale: string;
}

const QA_SYSTEM_PROMPT = `You are the Quality Assurance (QA) Match Agent for Thesis Compass. 
Your role is to act as an academic and professional critic. You receive a "Shortlisted Match" (a Student Profile and a Thesis Topic) generated by the Retrieval Agent. Your job is to rigorously evaluate the feasibility, alignment, and reality of this match, and then generate a structured, transparent explanation for the student.

=== INPUT DATA ===
You will receive a JSON payload containing Student Profile, Thesis Topic, and a Retriever Base Score.

=== YOUR TASKS ===
1. The Reality Check (Prerequisites vs. Reality): Cross-reference the topic's required technical/academic prerequisites against the student's actual GitHub distribution and degree. 
2. Trajectory Alignment: Evaluate if this topic aligns with the student's stated bio and #1/#2 ranked preferences.
3. The "Why" Synthesis: Translate your analysis into a concise, peer-to-peer explanation for the student.

=== STRICT RULES & WHAT NOT TO DO ===
- DO NOT HALLUCINATE SKILLS: If the topic requires C++ and the student only has Python, explicitly flag it.
- DO NOT BE OVERLY OPTIMISTIC: If it's 60% fit, label it a "stretch goal". 
- NO GENERIC PRAISE: Be specific about GitHub metrics.
- HONOR ACADEMIC BOUNDARIES: Use language like "strong candidate" or "aligns well".

=== EXPECTED OUTPUT FORMAT ===
You must respond strictly in valid JSON matching this schema:
{
  "final_confidence_score": [Integer 0-100],
  "match_tier": ["Perfect Fit", "Strong Candidate", "Stretch Goal", "Misaligned"],
  "technical_reality_check": {
    "is_feasible": [Boolean],
    "identified_gaps": [Array of strings],
    "strongest_assets": [Array of strings]
  },
  "student_facing_rationale": "message to student"
}`;

/**
 * Trigger the QA Match Agent via the backend proxy.
 */
export async function evaluateMatchWithQA(
  student: StudentProfile,
  topic: Topic,
  baseScore: number
): Promise<QAMatchResult> {
  // Construct the payload as requested by the LLM system prompt
  const payload = {
    student_profile: {
      degree: student.degree,
      university: student.universityName || student.universityId,
      prioritized_preferences: student.priorities || [],
      bio: student.about,
      github_context: student.github ? {
        languages: student.github.languageStats,
        commits_year: student.github.totalCommitsYear,
        topics: student.github.topics || []
      } : "Missing GitHub Data"
    },
    thesis_topic: {
      title: topic.title,
      company: topic.companyId || "University Research",
      prerequisites: [topic.description], // Mock data embeds requirements in description
      sector_tags: topic.fieldIds || [],
      description: topic.description
    },
    retriever_base_score: baseScore
  };

  try {
    // In a real app, this would be a POST to /api/match/qa
    // For the hackathon, we simulate or call a local endpoint if it exists.
    const response = await fetch('/api/match/qa', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        system: QA_SYSTEM_PROMPT,
        prompt: JSON.stringify(payload, null, 2)
      })
    });

    if (!response.ok) throw new Error('QA Agent failed to respond');
    return await response.json();
  } catch (error) {
    console.error('QA Agent Error:', error);
    // Fallback Mock Response for UI testing
    return {
      final_confidence_score: baseScore,
      match_tier: baseScore > 80 ? 'Perfect Fit' : 'Strong Candidate',
      technical_reality_check: {
        is_feasible: true,
        identified_gaps: [],
        strongest_assets: ["Matching skill profile"]
      },
      student_facing_rationale: "We're experiencing high load on our AI agents. Based on our vector match, this topic aligns strongly with your research interests."
    };
  }
}
