import { BaseMessage } from "@langchain/core/messages";
import { Annotation } from "@langchain/langgraph";

// Define the shape of our state based on the Mentorship Committee architecture.
export const ThesisState = Annotation.Root({
  // The original pitch that the student provided.
  initialPitch: Annotation<string>({
    reducer: (x, y) => y,
    default: () => "",
  }),

  // Generated by the Professor (RQs, Methodology, Timeline).
  academicRoadmap: Annotation<any>({
    reducer: (x, y) => y, // Always take the latest to allow iterations
    default: () => null,
  }),

  // Generated by the Assistant via OpenAlex.
  literatureContext: Annotation<any>({
    reducer: (x, y) => y,
    default: () => null,
  }),

  // Generated by the Chair (Risks, Scope constraints).
  defenseCritique: Annotation<any>({
    reducer: (x, y) => y,
    default: () => null,
  }),

  // The conversation history and intermediate tool invocations.
  messages: Annotation<BaseMessage[]>({
    reducer: (x, y) => x.concat(y),
    default: () => [],
  }),

  // Final synthesized status
  healthStatus: Annotation<"APPROVED" | "NEEDS_REVISION" | "REJECTED" | "PENDING">({
    reducer: (x, y) => y,
    default: () => "PENDING",
  })
});
